---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: coppy a file
      copy:
        src: /home/ansadmin/index.html
        dest: /home/ansadmin
        mode: 0666
        owner: akash
