---
- name: install httpd
  hosts: all
  become: true
  tasks:
    - name: install httpd in RedHat
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: htttp
        state: started
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: copy index.html
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
        mode: 0666

