---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: install packages
      yum: 
       name: ['git', 'make', 'gcc', 'wget', 'telnet', 'mysql', 'tree', 'which', 'docker']
       state: installed

